### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by Hept0p** [ElektroStudios/.NET-Assembly-Info-ShellEx#1]
**Installation Requeriments:**
.NET Framework 4.7
 --------
Tested on two Win7 machine (one VM, one Host, both 64-bit Enterprise). Both have the latest .NET Framework installed (4.7.2)...

None those two machine had the MS Visual Studio IDE installed though, only the Framework and all common runtime and dependencies. All Windows updates installed as well..

Any help would be appreciated.
Thanks

**Comment by ElektroStudios** [comment]
Thanks for your comment. It was a fault of mine, I didn't included a required file ('netstandard.dll') in the setup directory. This missing file was causing some assembly information retrieval to throw an exception, and thus leaving empty all the fields of the "Build" and "Identity" tabs.

The release is fixed, you can download it again from here:
 - https://github.com/ElektroStudios/.NET-Assembly-Info-ShellEx/releases/latest

To avoid possible problems, I suggest to do a clean reinstall: uninstall the previous version, restart the PC, and finally run the new setup.

PS: I tested both this setup and the shell-extension in Windows 7 Ultimate SP1 x64 with .NET Framework 4.7 (after applying a required update for NET 4.7 setup: Windows6.1-KB4019990-x64.msu)

Please, report here if the addition of the missing file 'netstandard.dll' resolved your problem. Otherwise, a better description of the problem will be required.

**Comment by Hept0p** [comment]
Shouldn't the code and build release commits been updated since ? I can't see any .. I do see the new package is larger when downloaded.. Why is that change not documented in the release ? I'm new to github.. Does a repo only use versionning to the Code page and not the release one ?..

**Comment by ElektroStudios** [comment]
Source-code is untouched, no change / commit has been made because the fix for the problem that you reported does not concern the source-code, but the distribution of the setup file. Note that the .NET Standard dependencies are already included in the bin directory of the solution (but anyway, Visual Studio automatically adds any missing dependency).

Yes, releases have versioning, however, since no single change was made to the source-code, this can not be called version 1.1, thus, I just preferred to edit the initial release to replace the uploaded zip file, rather than publishing a new one different release.

The change is very superficially documented in the release description, where you can read: 

> _( FIXED Setup, added missing 'netstandard.dll' file. )_

greetings!

**Comment by Hept0p** [comment]
Thanks :)
